# - 이미지 변형 (이진화)

In [1]:
import numpy as np
import cv2

img_path = './Data/book.jpg'

In [3]:
img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

ret, binary_img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

cv2.imshow('img', img)
cv2.imshow('binary_img', binary_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Trackbar (값 변화에 따른 변형 확인)

In [6]:
import cv2

def empty(pos):
    # pos : trackbark에서 받아오는 값
#     print(pos)
    pass

img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

name = 'Trackbar' # 빈 윈도우의 이름
cv2.namedWindow(name)

cv2.createTrackbar('threshold', name, 127, 255, empty) # bar 이름, 창의 이름, 초기값, 최대값, 이벤트 처리

while True:
    thresh = cv2.getTrackbarPos('threshold', name) # bar 이름, 창의 이름
    ret, binary = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)
    
    if not ret:
        break
        
    cv2.imshow(name, binary)
    if cv2.waitKey(1) == ord('q'):
        break
    
cv2.destroyAllWindows()

### Adaptive Threshold (Trackbar 사용)

영역을 세분화해서 임계치 적용

In [ ]:
import cv2

def empty(pos):
    # pos : trackbark에서 받아오는 값
#     print(pos)
    pass

img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

name = 'Trackbar' # 빈 윈도우의 이름
cv2.namedWindow(name)

# bar 이름, 창의 이름, 초기값, 최대값, 이벤트 처리
cv2.createTrackbar('block_size', name, 25, 100, empty) # 1보다 큰 홀수
cv2.createTrackbar('c', name, 3, 10, empty) # 일반적으로 양수 사용

while True:
    block_size = cv2.getTrackbarPos('block_size', name)
    c = cv2.getTrackbarPos('c', name)
    
    # 1보다 작거나 같은 값일 경우 3으로 변경
    if block_size <= 1:
        block_size = 3
        
    # 짝수일 경우 홀수로 변경
    if block_size % 2 == 0:
        block_size += 1
    
    binary = cv2.adaptiveThreshold(img,
                                    255,
                                    cv2.ADAPTIVE_THRESH_MEAN_C,
                                    cv2.THRESH_BINARY,
                                    block_size,
                                    c)
        
    cv2.imshow(name, binary)
    if cv2.waitKey(1) == ord('q'):
        break
    
cv2.destroyAllWindows()

### 오츠 알고리즘

최적의 임계치 값을 찾는 알고리즘 - Bimodal Image 에 사용하기 적합

In [8]:
import numpy as np
import cv2

img_path = './Data/book.jpg'

In [10]:
img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

ret, binary_img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
ret, otsu = cv2.threshold(img, -1, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
print('otsu threshold: ', ret)

cv2.imshow('img', img)
cv2.imshow('binary_img', binary_img)
cv2.imshow('otsu', otsu)

cv2.waitKey(0)
cv2.destroyAllWindows()

otsu threshold:  100.0


# - 이미지 변환 (팽창 Dilating)

이미지를 확장하여 작은 구멍을 채움

흰색 영역의 외곽 픽셀 주변에 흰색을 채움

In [11]:
kernel = np.ones((3, 3), dtype = np.uint8)

# kernel 을 이용해 각 픽셀에 대해서 중심 픽셀 정보를 주변으로 팽창 시키는 작업
dilate = cv2.dilate(img, kernel, iteration = 1) # iteration = 반복 횟수`

# - 이미지 변환 (침식 Eroding)

이미지를 깎아서 노이즈 제거

흰색 영역의 외곽 픽셀 주변을 검은색으로 변경

In [13]:
kernel = np.ones((3, 3), dtype = np.uint8)
print(kernel)

erode = cv2.erode(img, kernel, iterations = 1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# - 이미지 변환 (열림과 닫힘)

위 팽창과 침식을 동시에 연산
- 열림(Opening) : 침식 후 팽창
- 닫힘(Closing) : 팽창 후 침식