In [2]:
import numpy as np

### np.newaxis

넘파이 배열의 차원을 확장하는 기능

*reshape 과의 차이점은?
- reshape의 경우 특정 shape으로 배열을 변경하는 것
- newaxis의 경우 새로운 차원 '1개'를 배열에 추가하는 것 (빈 열 하나 추가)

In [3]:
arr = np.arange(1, 5)

print(arr, arr.shape) # 1차원 배열의 형태

[1 2 3 4] (4,)


In [36]:
arr_newaxis = arr[np.newaxis, :] # 빈 열 * 기존 array의 사이즈
arr_reshape = arr.reshape(1, 4)

print(arr.shape, arr_newaxis.shape, arr_reshape.shape)
print(arr_newaxis)

(4,) (1, 4) (1, 4)
[[1 2 3 4]]


In [37]:
arr_newaxis = arr[:, np.newaxis]
arr_reshape = arr.reshape(4, 1)

print(arr.shape, arr_newaxis.shape, arr_reshape.shape)

(4,) (4, 1) (4, 1)


In [40]:
# broad casting을 할 때 필요하다.
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

print(x1.shape, x2.shape)
print(x1 * x2)

(5,) (3,)


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [44]:
x1_new = x1[:, np.newaxis] # 5 * 1 의 2차원 배열로 변경

print(x1_new.shape)
print(x1_new)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [43]:
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [45]:
x1_new * x2

array([[ 5,  4,  3],
       [10,  8,  6],
       [15, 12,  9],
       [20, 16, 12],
       [25, 20, 15]])